name: arcana_the_three_hearts
description: "2D Top-down Pixel Art Action RPG - Arcana: The Three Hearts"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  flame_audio: ^2.10.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  flutter_riverpod: ^2.4.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/itchio/0x72_DungeonTilesetII_v1.7/0x72_DungeonTilesetII_v1.7/frames/
    - assets/images/itchio/0x72_DungeonTilesetII_v1.7/0x72_DungeonTilesetII_v1.7/
    - assets/config/
    - assets/bgm/
    - assets/sfx/
    - assets/audio/bgm/
    - assets/audio/sfx/
